import { Analytics } from "@vercel/analytics/react"
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import en_US from 'antd/locale/en_US';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ConfigProvider locale={en_US}>
            {children}
            {/* <Analytics /> */}
          </ConfigProvider>
        </AntdRegistry>

      </body>
    </html >
  );
}
