const IndustyOptions = [
  { value: "-None-", label: "-None-" },
  { value: "Agricultural", label: "Agricultural" },
  { value: "Automotive", label: "Automotive" },
  { value: "Aviation", label: "Aviation" },
  { value: "Building and Construction", label: "Building and Construction" },
  { value: "Chemical manufacturer", label: "Chemical manufacturer" },
  {
    value: "Commercial & Professional Services",
    label: "Commercial & Professional Services",
  },
  { value: "Consumer Goods", label: "Consumer Goods" },
  { value: "Cosmetic", label: "Cosmetic" },
  { value: "Defense", label: "Defense" },
  { value: "Electrical Equipment", label: "Electrical Equipment" },
  { value: "Electronics", label: "Electronics" },
  { value: "Energy", label: "Energy" },
  { value: "Environment", label: "Environment" },
  { value: "Food and Beverage", label: "Food and Beverage" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Hospital", label: "Hospital" },
  { value: "IT", label: "IT" },
  { value: "Jewelry", label: "Jewelry" },
  { value: "Lab equipment manufacturer", label: "Lab equipment manufacturer" },
  { value: "Lab service", label: "Lab service" },
  { value: "Logistic", label: "Logistic" },
  { value: "Marketing", label: "Marketing" },
  { value: "Mining", label: "Mining" },
  { value: "NGO", label: "NGO" },
  { value: "Nuclear", label: "Nuclear" },
  { value: "Other", label: "Other" },
  { value: "Other Distributor", label: "Other Distributor" },
  { value: "Other Education", label: "Other Education" },
  {
    value: "Other Manufacturing (Not matched to another industry)",
    label: "Other Manufacturing (Not matched to another industry)",
  },
  { value: "Petroleum", label: "Petroleum" },
  { value: "Pharmaceutical", label: "Pharmaceutical" },
  { value: "Plastic and Rubber", label: "Plastic and Rubber" },
  { value: "Printing", label: "Printing" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Research center", label: "Research center" },
  { value: "Retail", label: "Retail" },
  { value: "School", label: "School" },
  { value: "Scientific Distributor", label: "Scientific Distributor" },
  { value: "Security", label: "Security" },
  { value: "Textile", label: "Textile" },
  { value: "University", label: "University" },
  { value: "Waste management", label: "Waste management" },
  { value: "Water Utilities", label: "Water Utilities" },
  { value: "Zoo", label: "Zoo" },
];

export default IndustyOptions;
